// modelsData.js
const modelsData = 

{
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Mito", "Giulietta", "4C", "Spider"],
  "Aston Martin": ["Vantage", "DB11", "Rapide", "DBX", "Vanquish"],
  "Acura": ["ILX", "TLX", "MDX", "RDX", "NSX", "ZDX"],
  "Am General": ["Hummer H1", "Hummer H2", "Hummer H3"],
  "Abarth": ["595", "124 Spider", "500", "695", "Punto"],
  "Apollo Automobil": ["Apollo IE", "Intensa Emozione"],
  "Audi Sport": ["RS3", "RS5", "RS7", "RSQ8", "R8 V10"],
  "Austin": ["Mini", "A30", "A40", "A50", "Morris Minor"],
  "BMW": ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "i3", "i4", "i8", "M3", "M5", "M8", "X6"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  "Bugatti": ["Chiron", "Veyron", "Divo", "Bolide"],
  "Buick": ["Encore", "Enclave", "Regal", "LaCrosse", "Cascada"],
  "Chevrolet": ["Cruze", "Malibu", "Impala", "Equinox", "Tahoe", "Suburban", "Silverado", "Traverse", "Camaro", "Corvette", "Colorado", "Blazer"],
  "Chrysler": ["300", "Pacifica", "Voyager", "Aspen"],
  "Caterham": ["Seven 160", "Seven 310", "Seven 420", "Seven 620"],
  "Cadillac": ["CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6", "XT7", "Lyriq"],
  "Dodge": ["Charger", "Challenger", "Durango", "Ram", "Journey", "Grand Caravan"],
  "Daimler": ["Daimler Super Eight", "Daimler V8", "Daimler SP250"],
  "DeLorean": ["DeLorean DMC-12"],
  "Dacia": ["Sandero", "Lodgy", "Dokker", "Spring", "Logan"],
  "DS Automobiles": ["DS 3", "DS 4", "DS 5", "DS 7 Crossback", "DS 9"],
  "Daihatsu": ["Terios", "Cuore", "Charade", "Move", "Rocky", "Sirion", "Materia"],
  "Eagle": ["Talon", "Vision", "Summit", "Premier"],
  "Edsel": ["Citation", "Pacer", "Ranger", "Corsair", "Villager"],
  "Exige": ["Exige S", "Exige 410", "Exige Sport 350"],
  "Eterniti Motors": ["Eterniti Artemis"],
  "Electric Vehicles": ["Tesla Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  "Ford": ["F-150", "Mustang", "Explorer", "Escape", "Fusion", "Ranger", "Focus", "Edge", "Bronco", "Maverick", "Expedition"],
  "Ferrari": ["488 GTB", "F8 Tributo", "Portofino", "Roma", "812 Superfast", "LaFerrari", "GTC4Lusso", "SF90 Stradale"],
  "Fiat": ["500", "Panda", "Tipo", "Doblo", "Freemont", "500X", "500L", "Punto"],
  "Fisker": ["Ocean", "Karma", "Fisker EMotion"],
  "GMC": ["Sierra", "Yukon", "Canyon", "Acadia", "Terrain", "Envoy"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "General Motors": ["Chevrolet", "Buick", "GMC", "Cadillac"],
  "Honda": ["Civic", "Accord", "CR-V", "Pilot", "HR-V", "Insight", "Fit", "Odyssey", "Ridgeline"],
  "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Kona", "Ioniq", "Palisade", "Veloster", "Kona Electric"],
  "Hummer": ["H1", "H2", "H3", "Hummer EV"],
  "Isuzu": ["D-Max", "MU-X", "Ascender", "Trooper", "N-Series", "F-Series"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX60", "QX80", "Q70"],
  "Iveco": ["Daily", "Stralis", "Trakker", "Eurocargo"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace"],
  "Kia": ["Optima", "Seltos", "Sorento", "Sportage", "Stinger", "Telluride", "Niro", "Soul", "Forte"],
  "Koenigsegg": ["Agera RS", "Jesko", "Regera", "One:1", "Gemera"],
  "Karma": ["Revero", "GS-6", "SC1 Vision"],
  "Lexus": ["IS", "ES", "GS", "RX", "NX", "LX", "UX", "LC", "LS", "LX570"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Evoque", "Velar", "Sport"],
  "Lincoln": ["Navigator", "Corsair", "Aviator", "Continental", "MKZ", "MKC"],
  "Lotus": ["Elise", "Exige", "Evora", "Emira"],
  "Lamborghini": ["Aventador", "Huracán", "Urus", "Sián", "Gallardo", "Murciélago"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "GranTurismo", "Alfieri", "MC20"],
  "McLaren": ["720S", "P1", "570S", "Artura", "Senna", "Speedtail"],
  "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5 Miata", "CX-50", "Mazda2"],
  "MINI": ["Cooper", "Countryman", "Clubman", "Convertible", "John Cooper Works"],
  "Mitsubishi": ["Outlander", "Eclipse Cross", "Lancer", "Pajero", "ASX", "Mirage"],
  "Nissan": ["Altima", "Maxima", "370Z", "Leaf", "Rogue", "Murano", "Pathfinder", "Titan", "Armada", "Frontier"],
  "Noble": ["M600", "M12", "M10"],
  "Pagani": ["Huayra", "Zonda", "Huayra Roadster", "Imola"],
  "Peugeot": ["208", "308", "508", "2008", "3008", "5008", "Partner"],
  "Porsche": ["911", "Cayenne", "Macan", "Taycan", "Panamera", "Boxster", "Cayman", "718"],
  "Polestar": ["Polestar 1", "Polestar 2", "Polestar 3"],
  "Pontiac": ["G6", "Grand Prix", "Firebird", "Trans Am", "Fiero", "Vibe"],
  "Opel": ["Astra", "Corsa", "Insignia", "Mokka", "Grandland X", "Adam", "Zafira"],
  "Porsche": ["911", "Cayenne", "Macan", "Taycan", "Panamera", "Boxster", "Cayman", "718"],
  "Polestar": ["Polestar 1", "Polestar 2", "Polestar 3"],
  "Peugeot": ["208", "308", "508", "2008", "3008", "5008", "Partner"],
  "Plymouth": ["Barracuda", "Road Runner", "Cuda", "Fury", "Valiant"],
  "Pontiac": ["G6", "Grand Prix", "Firebird", "Trans Am", "Fiero", "Vibe"],
  "Pagani": ["Huayra", "Zonda", "Huayra Roadster", "Imola"],
  "Renault": ["Clio", "Megane", "Captur", "Talisman", "Koleos", "Kadjar", "Zoe", "Laguna"],
  "Rivian": ["R1T", "R1S"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
  "Rover": ["Range Rover", "Defender", "Discovery", "Evoque", "Sport", "Velar"],
  "Subaru": ["Impreza", "Outback", "Forester", "Crosstrek", "Legacy", "BRZ", "Ascent"],
  "Saab": ["9-3", "9-5", "9-7X", "900", "Sonett"],
  "Suzuki": ["Swift", "Vitara", "S-Cross", "Ignis", "Jimny", "Baleno", "Alto", "SX4"],
  "Saleen": ["S7", "Mustang Saleen", "F7", "S1"],
  "Spyker": ["C8", "D8", "B6 Venator"],
  "Smart": ["Fortwo", "Forfour", "Roadster"],
  "SsangYong": ["Korando", "Tivoli", "Rexton", "Musso", "Chairman"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
  "Toyota": ["Corolla", "Camry", "Prius", "Land Cruiser", "Hilux", "Tacoma", "RAV4", "Highlander", "Sequoia", "Sienna", "Avalon", "Supra"],
  "Tata Motors": ["Nexon", "Harrier", "Safari", "Tigor", "Tiago", "Hexa", "Altroz"],
  "Triumph": ["TR6", "TR4", "Spitfire", "GT6"],
  "TVR": ["Chimaera", "Tuscan", "Sagaris", "Cerbera", "Grantura"],
  "Vauxhall": ["Astra", "Corsa", "Insignia", "Mokka", "Grandland", "Zafira"],
  "Volvo": ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "Polestar 1", "Polestar 2"],
  "Volkswagen": ["Golf", "Passat", "Jetta", "Tiguan", "Touareg", "Arteon", "Polo", "ID.4", "ID.3", "Beetle", "CC"],
  "VinFast": ["Lux A2.0", "Lux SA2.0", "VF e34", "VF e35", "VF e36"],
  "Vector Motors": ["W8", "M12", "AVC"]
}